FROM node:16
WORKDIR /app

# Setup pnpm package manager
RUN npm install -g pnpm@7.5.2

# Setup proxy to API used in saleor-platform
RUN apt-get update && apt-get install -y nginx
COPY apps/storefront/nginx/dev.conf /etc/nginx/conf.d/default.conf

COPY . .
RUN pnpm install


ARG SALEOR_API_URL
ENV SALEOR_API_URL ${SALEOR_API_URL:-https://test-env-01.saleor.cloud/graphql/}

ARG NEXT_PUBLIC_STOREFRONT_NAME
ENV NEXT_PUBLIC_STOREFRONT_NAME 'Bibotta Studio'

ARG NEXT_PUBLIC_CHECKOUT_APP_URL
ENV NEXT_PUBLIC_CHECKOUT_APP_URL http://172.17.0.2:3001

ARG NEXT_PUBLIC_CHECKOUT_URL
ENV NEXT_PUBLIC_CHECKOUT_URL http://172.17.0.2:3001/checkout-spa

EXPOSE 3000
CMD pnpm turbo run dev --parallel --cache-dir=.turbo
